### ISSUE TITLE
Entity missing after restart of HA

### ISSUE THREAD

**Issue by everythingwebza** [puttyman/hass-amplifi#15]
I have noted the caveat that says the session will be invalidated if you log in which I assume might be happening. I have not logged in to the AmpliFi web interface at all though. 

Error shown in logs:
`Logger: homeassistant.config_entries
Source: custom_components/amplifi/coordinator.py:63
Integration: Amplifi (documentation, issues)
First occurred: 09:05:16 (1 occurrences)
Last logged: 09:05:16

Error setting up entry 10.23.23.65 for amplifi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/amplifi/__init__.py", line 32, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 156, in async_config_entry_first_refresh
    await self._async_refresh(log_failures=False, raise_on_auth_failed=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/amplifi/coordinator.py", line 63, in extract_wifi_devices
    raw_wifi_devices = self.data[WIFI_DEVICES_IDX]
TypeError: 'NoneType' object is not subscriptable
`

If I remove the integration and re-set it up again it works immediately.
As soon as I restart Home Assistant the entity is not available and the above error is in the logs. 
I've restarted the entire host and it still does not come back. Seems only if I remove the integration and re-setup it will work until such time as HA restarts.

I am running an AmpliFi Router HD (HW Revision 19) with Firmware 3.6.2

**Comment by joelphillipsABHS** [comment]
I have the same issue. I have been dealing with it the same way by disabling and then enabling. It would be awesome to have this resolve. I tried to find a service that is able to restart an integration so that I could automate the process 60 seconds after HA starts up but was unsuccessful.

**Comment by Hubszo** [comment]
Exactly same issue - after HA restart Amplifi failed to set up:
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/amplifi/coordinator.py:63
Integration: Amplifi (documentation, issues)
First occurred: 13 January 2022, 16:30:40 (8594 occurrences)
Last logged: 18:07:27

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/config/custom_components/amplifi/coordinator.py", line 63, in extract_wifi_devices
    raw_wifi_devices = self.data[WIFI_DEVICES_IDX]
TypeError: 'NoneType' object is not subscriptable

**Comment by gadgetchnnel** [comment]
I've created a PR which checks whether self.data is not None before continuing and should fix this.
There will still be a message in the log like `Config entry 'amplifi.lan' for amplifi integration not ready yet: Failed to init amplifi client session.; Retrying in background` but the entities will be available following the retry.

**Comment by puttyman** [comment]
@defusiondev there was a PR just merged see that if fixes it for you. Closing for now.

**Comment by everythingwebza** [comment]
So far so good, thanks @puttyman
