### ISSUE TITLE
Bridge mode

### ISSUE THREAD

**Issue by teaching-innovation** [puttyman/hass-amplifi#23]
I have assigned DHCP serving to my firewall. In the AMPLIFI app I can still see all devices but since making this change I can not see devices in Home assistant.  

Is there a simple change I can make to allow the integration to continue working while the AMPLIFI router is in bridge mode?

**Comment by C0NTi** [comment]
I am using hass-amplifi in bridge mode without any issue.

I set the AMPLIFI to have a static IP address 

e.g.

from 

amplifi as router on 192.x.x.1

to

router as 192.x.x.1
Amplifi as 192.x.x.2

I deleted the original Amplifi integration

restart home assistant

re-added the Amplifi integration adding the new IP address from Bridge mode.

![image](https://user-images.githubusercontent.com/29498865/195120371-a1b5e003-7048-47be-b0a4-0023bcb36c90.png)

**Comment by teaching-innovation** [comment]
I tried that again. 
The integration does start and lists 49 devices but then doesn't seem to update and most devices are offline unless they are connected with another integration. 

This is the error I am getting. Sorry I should have posted in my initial comment:

```

This error originated from a custom integration.

Logger: custom_components.amplifi.coordinator
Source: custom_components/amplifi/client.py:81 
Integration: Amplifi (documentation, issues) 
First occurred: 08:48:42 (4 occurrences) 
Last logged: 08:49:12

Unexpected error fetching amplifi data: Session is closed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/amplifi/coordinator.py", line 55, in _async_update_data
    devices = await self._client.async_get_devices()
  File "/config/custom_components/amplifi/client.py", line 26, in async_get_devices
    return await self._async_get_info()
  File "/config/custom_components/amplifi/client.py", line 81, in _async_get_info
    resp = await self._client.post(info_async_url, data=form_data)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

```

**Comment by teaching-innovation** [comment]
![image](https://user-images.githubusercontent.com/4116145/195459008-bc5e1ef1-7e8c-44bc-bd2d-b4792f8aae95.jpeg)

**Comment by hawksj** [comment]
Error "session is closed" may be a result of the notice in the caveats section in the README, when logging in with the mobile app. I have not been able to replicate this error in my own instance. Due to the age of this issue and that it's had no action in almost 2 years, I will close this issue. If this is still an issue or other users experience it, please report it again.
