### ISSUE TITLE
How can I make a list of connected devices?

### ISSUE THREAD

**Issue by Flashlab2** [puttyman/hass-amplifi#25]
I would like to have a list of devices connected to Amplifi in my HA dashboard. The documentation seems to hint that this is possible. I do see a list of entities created by the Integration but by default most of them are disables. So I manually enabled some of them and I can check status for them but I would like to have the list of all connected devices updated automatically if possible.

And it would then be really neat if I could get a notification if a new device connects to my Amplifi.

Is this possible?

**Comment by plesetsk** [comment]
Hi 
you can use this template

{{states.device_tracker
                 | selectattr('entity_id', 'match', 'device_tracker.amplifi.*')
                 | selectattr('state', 'eq', 'home')
                 | map(attribute='name')
                 | list }}

**Comment by Flashlab2** [comment]
Thanks this works!

**Comment by hawksj** [comment]
Closing as answered
