### ISSUE TITLE
Security (Create alerts for unknown devices connected to your wifi)

### ISSUE THREAD

**Issue by davidrule1969** [puttyman/hass-amplifi#27]
How do I set this up?  What trigger would I use to send a notification when an unknown device connects to my Wifi?

**Comment by plesetsk** [comment]
> How do I set this up? What trigger would I use to send a notification when an unknown device connects to my Wifi?
Hello, I faced with the same question. 

You can use this https://github.com/puttyman/hass-amplifi/pull/31/files to automatically enable new connected devices. 

After this you can use a trigger in automatisation to create alerts and notifications 

`alias: New device registered
description: ""
trigger:
  - platform: event
     event_type: entity_registry_updated
     event_data:
       action: create
condition:  
  - condition: template
      value_template: "{{trigger.event.data.entity_id.startswith('device_tracker')}}"
action:
  - service: notify.notify_telegram    
     data:
       message: >- 
         id:        {{(trigger.event.data.entity_id).replace('_','-')}}{{'\n'}} 
         Host:        {{state_attr(trigger.event.data.entity_id,'host_name')}}{{'\n'}} 
         Ip:        {{state_attr(trigger.event.data.entity_id,'ip')}} {{'\n'}} 
         Mac:        {{state_attr(trigger.event.data.entity_id,'mac')}}             
mode: queued
`

**Comment by plesetsk** [comment]
#31
