### ISSUE TITLE
Device tracker vs. sensor

### ISSUE THREAD

**Issue by sungla55guy** [puttyman/hass-amplifi#3]
Can this be changed so that entities show up as device trackers and can work with persons instead of sensors?

**Comment by warlo** [comment]
With very little effort and probably suboptimally – I modified this to work with device trackers. https://github.com/hanswilw/hass-amplifi/

**Comment by davenbo** [comment]
> With very little effort and probably suboptimally – I modified this to work with device trackers. https://github.com/hanswilw/hass-amplifi/

This is me being not educated enough on github/hacs but how do I install your fork to benefit from that?

**Comment by warlo** [comment]
> This is me being not educated enough on github/hacs but how do I install your fork to benefit from that?

I just install stuff manually by copying it into the custom_components folder

**Comment by puttyman** [comment]
2.0.0 will now use device trackers
