### ISSUE TITLE
WAN Rx / Tx sensors no longer working (post HA 2023.7.0 update)

### ISSUE THREAD

**Issue by DaveAuld** [puttyman/hass-amplifi#34]
Updated to HA 2023.7 and now the integration sensors for WAN Tx/Rx no longer work.

Any pointers on what I need to do, if anything, from my side to fix, or is this a change required in the integration?

![image](https://github.com/puttyman/hass-amplifi/assets/4674288/c4dff8b4-5d3c-4a25-ad55-dd36255190b4)

![image](https://github.com/puttyman/hass-amplifi/assets/4674288/919a854a-92a8-45d4-a935-e2aa667913e9)

**Comment by everythingwebza** [comment]
same issue here

![image](https://github.com/puttyman/hass-amplifi/assets/9987268/0504cad0-d4d7-44ac-bcc7-1bc711dcd00b)

**Comment by atudor2** [comment]
I have created a PR to resolve this - in the meantime, you can edit the file custom_components\amplifi\sensor.py to make name a property and restart HA

**Comment by DaveAuld** [comment]
Thanks, made the file changes as per the PR commits, all good now.

**Comment by everythingwebza** [comment]
> I have created a PR to resolve this - in the meantime, you can edit the file custom_components\amplifi\sensor.py to make name a property and restart HA

sorted - thanks
