### ISSUE TITLE
Amplifi not Showing in Integrations after Install

### ISSUE THREAD

**Issue by norsemangrey** [puttyman/hass-amplifi#4]
Hi. I am running on Hass.io (0.117.6). I was able to add the repository and install the component through HACS and it shows up under installed HACS integrations (and I checked the folder is also in the correct location), but even after restarting I am not able to search for it under Configuration -> Integration. I followed the instructions for installation, restarted HA, navigated to Configuration -> Integration, clicked the + and searched for Amplifi, but nothing shows up.

**Comment by jnschioett** [comment]
Hi!
Did you get any response or figured out why?
I'm in the same position - everything installed - can't find the integration!

Regards,
Jesper

**Comment by davidrule1969** [comment]
Same problem here.  2021.6.4.

**Comment by calisro** [comment]
No one?  Added version to manifest and tried to add config data to configuration.yaml.  I can see in the logs HA loaded the component but the integration doesn't show nor do any entities or errors

**Comment by darren131** [comment]
@puttyman any thoughts on this, please?

**Comment by puttyman** [comment]
@darren131 I believe its due to https://github.com/puttyman/hass-amplifi/issues/8 . I am working on a new version which should hopefully address this issue and:

- Have presence for ethernet
- Internet speed sensors
- Using device tracker instead of sensor for wifi/eth enitities

Hopefully this weekend.

**Comment by darren131** [comment]
oh nice one! Thanks for the update :)

**Comment by jmottster** [comment]
I'm having this same issue. As of 9/2/2021. Running HA version core-2021.8.8

**Comment by townsmcp** [comment]
Same here. Adding version 1.0.0 in the manifest still does not show up the integration after rebooting HASS

**Comment by jmottster** [comment]
If it's helpful, this error is in my logs:

2021-09-05 09:53:15 ERROR (SyncWorker_3) [homeassistant.loader] The custom integration 'amplifi' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by jpsmith16** [comment]
@puttyman thanks for your work on this. just wondering if you’re any closer to releasing a new version as mentioned above?

**Comment by puttyman** [comment]
Sorry been busy and HA had many changes. Instead of making this integration perfect which is unlikely going to happen soon, I have now released the newer version and seems to be stable to me.

Keen to hear the feedbacks.
