### ISSUE TITLE
Deprecation constants warning since 2024.1

### ISSUE THREAD

**Issue by arboeh** [puttyman/hass-amplifi#43]
Since update to HA 2024.1 there is a deprecation warning:

`SOURCE_TYPE_ROUTER was used from amplifi, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/puttyman/hass-amplifi/issues`

This constants warning affects many integrations and also for the Amplifi integration.

**Comment by hawksj** [comment]
The other deprecating component that will need to be replaced:
`DATA_RATE_MEGABITS_PER_SECOND was used from amplifi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEGABITS_PER_SECOND instead, please report it to the author of the 'amplifi' custom integration`

Should be an easy change as in PR 44.
