### ISSUE TITLE
Consider home-option

### ISSUE THREAD

**Issue by davenbo** [puttyman/hass-amplifi#5]
Hello, thanks so much for this integration. I bought the amplifi without checking/realizing there isn't a device-tracker component readily available so you saved my day(s).

The sensor seems really stable, but I have had a few times where my phone maybe sleeps or saves battery and it tracks as away even though I'm at home.

Is there any way to set a "consider home" timeout-period like with the standard device tracker? So that it ignores disconnected devices until they've been away for that amount of time.

**Comment by puttyman** [comment]
You could always have a duration before triggering any actions. For example if devices disconnected for 5 mins then do action turn light off.

See: https://community.home-assistant.io/t/understanding-the-for-time-based-condition/143986

**Comment by puttyman** [comment]
Feature in 2.0.0
