### ISSUE TITLE
Pause Internet Support

### ISSUE THREAD

**Issue by gbertsch** [puttyman/hass-amplifi#54]
Is it possible to support pausing internet per Device, or per Device Group (should one be created)?

**Comment by hawksj** [comment]
Hi @gbertsch 

This integration is currently entirely read only (from the routers perspective) and gets all data from a basic text file. We've previously been asked about adding the ability to reboot the router from this integration but I think both of these features would require significant overhauls of the integration. Recent additions only modify the parsing of the text file.

That is to say it's not something I am planning to add and I've not seen any other contributors express an intention to do so either. If you are a developer and can have a crack at it, I'd be happy to receive and merge a PR but from our side, it's kind of beyond scope.

Apologies,
Sam
