### ISSUE TITLE
Amplifi hostname

### ISSUE THREAD

**Issue by Hubszo** [puttyman/hass-amplifi#6]
I'm having issue with the last step when entering hostname and password. I can't find in AmpliFi app any details regarding hostname. Do you mean 'Device name' under Settings > General???

**Comment by townsmcp** [comment]
@Hubszo try entering the IP of your Amplifi router (probably 192.168.1.1 or some such x.x.x.1)

**Comment by Hubszo** [comment]
Thanks for your quick reply, unfortunately IP doesn't work. And both IP and password are correct since I can access web gui.

**Comment by townsmcp** [comment]
@Hubszo did you try 'http://192.168.1.1' or just the ip?

**Comment by Hubszo** [comment]
Of course I used my IP address and not word IP :) which in my case is 172.20.0.1
![image](https://user-images.githubusercontent.com/26574723/108000399-2644b700-6fea-11eb-8a5b-2486bf1e19bb.png)

**Comment by Hubszo** [comment]
and I tried both with and without http://

**Comment by Hubszo** [comment]
Hello again,
Any suggestion on how I can get this working?

**Comment by C0NTi** [comment]
How are you running home assistant?

Its not on a different docker network or something where it cant reach your router's webportal?

**Comment by Hubszo** [comment]
Sorry for late reply. I was away for 2 weeks :)
Anyway, I'm running HA in VirtualBox. VB is installed on my server running Windows 10Pro. I can just reach Amplifi webportal using either local IP the gateway or by typing amplifi.lan. In both cases I'm prompt with window where I have to pick Amplifi router (http://amplifi.lan/select-device.php) and then login screen (http://amplifi.lan/login.php) where only password is given.

**Comment by Jeticus** [comment]
Sorry to revive an old issue but after some troubleshooting I managed to track down the issue (atleast in my case) to different HA running on a different subnet to the Amplifi. Regardless of having the appropriate network rules in place to allow for communication between subnets, if the Amplifi is not on the same subnet as HA it refuses to work.

My workaround was to use a source NAT to translate the HA device to masquerade as an IP on the Amplifi network. Not ideal but a workaround if anyone still needs to do the same.

**Comment by Jeticus** [comment]
Sorry to revive an old issue but after some troubleshooting I managed to track down the issue (atleast in my case) to HA running on a different subnet to the Amplifi. Regardless of having the appropriate network provisions in place to allow for communication between subnets, if the Amplifi is not on the same subnet as HA, the integration refuses to work.

My workaround was to use a source NAT to translate the HA device to masquerade as an IP on the Amplifi network. Not ideal but a workaround if anyone still needs to do the same.

**Comment by puttyman** [comment]
@Hubszo sounds like your issue is with your specific network environment rather than this add-on. Closing it.
