### ISSUE TITLE
Needs updating to continue working within HA

### ISSUE THREAD

**Issue by MichaelNMaggs** [puttyman/hass-amplifi#8]
Loading now gives the message `" ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'amplifi'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'amplifi' "`

I'd really like to continue using this, so I hope iut will be possible to update it.

Michael

**Comment by C0NTi** [comment]
@MichaelNMaggs - Until this gets updated properly you should be able to upgrade to version 2021.6 simply by finding the manifest.json file within the custom_components\amplifi folder and adding "version": "1.0" somewhere in the json file.

![image](https://user-images.githubusercontent.com/29498865/120548124-e57e7b80-c3e9-11eb-8704-f98a67c2793b.png)

**Comment by captennemo** [comment]
According to the HA docs you should add "version": "1.0.0" (not 1.0) as it requirers "major, minor, patch" arguments

**Comment by townsmcp** [comment]
Adding version the way in the pic, and ensure it is 1.0.0 is not showing up the integration

**Comment by puttyman** [comment]
Fixed in 2.0.0
